# vars for user credentials to access twitter api
ACCESS_TOKEN = "3116634531-NVNXXhjCooHF05YvFxD2WVfMeQ6v44WXbwfWLaB"
ACCESS_TOKEN_SECRET = "UZsnGz1qYufgPPPm0qLdbs1vWUJwG6vY5TwknluKsqfSq"
CONSUMER_KEY = "wIRRJYhT6HIWhNFiNFBQONcHA"
CONSUMER_SECRET = "doHc3DoOYHGRVwAWSHNdGcIjSowXhoFTsRirpuZkWIO0kSvDmz"